-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 16:42:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_grupos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_grupos` ;

-- -----------------------------------------------------
-- Schema bd_grupos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_grupos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish2_ci ;
USE `bd_grupos` ;

-- -----------------------------------------------------
-- Table `bd_grupos`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_grupos`.`grupo` ;

CREATE TABLE IF NOT EXISTS `bd_grupos`.`grupo` (
  `id` INT(6) NOT NULL AUTO_INCREMENT,
  `secuencia` INT(6) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cupo` INT(2) NOT NULL DEFAULT 5,
  `activo` BIT(1) NULL DEFAULT b'1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `secuencia_UNIQUE` (`secuencia` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_grupos`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_grupos`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `bd_grupos`.`estudiante` (
  `id` VARCHAR(15) NOT NULL,
  `nrc` INT(6) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `secuencia` INT(6) NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  `ultimo_acceso` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `grupo_id` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante_grupo_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_grupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `bd_grupos`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `bd_grupos` ;

-- -----------------------------------------------------
-- Placeholder table for view `bd_grupos`.`general_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_grupos`.`general_estudiante` (`nrc` INT, `secuencia` INT, `id` INT, `apellidos` INT, `nombre` INT, `ultimo_acceso` INT, `grupo_id` INT);

-- -----------------------------------------------------
-- View `bd_grupos`.`general_estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_grupos`.`general_estudiante`;
DROP VIEW IF EXISTS `bd_grupos`.`general_estudiante` ;
USE `bd_grupos`;
CREATE  OR REPLACE VIEW `general_estudiante` AS 
	SELECT  `nrc`, `secuencia`, `id`, `apellidos`, `nombre`, `ultimo_acceso`, `grupo_id`
    FROM estudiante
    ORDER BY `nrc`, `secuencia`
    ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
